"""reinit

Revision ID: ae02c89aa755
Revises: af91df62edd1
Create Date: 2023-06-18 00:33:16.077844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae02c89aa755'
down_revision = 'af91df62edd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
