"""make-relation

Revision ID: cd6a006800ac
Revises: 84cb02adbbd0
Create Date: 2023-06-17 23:49:10.219506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6a006800ac'
down_revision = '84cb02adbbd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
